# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a62c3403dd70b6ddaf1cd51d2ec29c4aeefb2355f09e49e626c39073708e3c363596fa32e69ea53a7610d6f4654e7b9f86f56ff89f26171d5775fe85028125ea

test:
  secret_key_base: d911de56a6f60c1fd12d0bdaa2240a4d886962ede38d7c43af744e7a4ba2f4ca5aed4ec91156305048014577417d261a80ab124274e700865d18188719c52e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
